# Generated by Django 4.1.5 on 2023-01-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeautyBarterAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barter',
            name='products',
            field=models.ManyToManyField(through='BeautyBarterAPI.BarterProduct', to='BeautyBarterAPI.product'),
        ),
    ]
