# Generated by Django 4.1.5 on 2023-02-01 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BeautyBarterAPI', '0002_barter_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='member',
        ),
        migrations.AddField(
            model_name='product',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
